In [ ]:
import pandas as pd

In [ ]:
# 한국 ESG 기준원 데이터 불러오기 
# 10990개 
evaluate_df = pd.read_excel('evaluate_data.xlsx',dtype={
    '기업코드' : str
})
evaluate_df.head()

C:\Users\SAMSUNG\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NO,기업명,기업코드,ESG등급,환경,사회,지배구조,평가년도,ESG 등급조정,환경 등급조정,사회 등급조정,지배구조 등급조정
0,10990.0,AJ네트웍스,095570,미공개,미공개,미공개,C,2016.0,NaN,NaN,NaN,NaN
1,10989.0,AJ네트웍스,095570,미공개,미공개,미공개,B,2017.0,NaN,NaN,NaN,NaN
2,10988.0,AJ네트웍스,095570,미공개,미공개,미공개,C,2018.0,NaN,NaN,NaN,NaN
3,10987.0,AJ네트웍스,095570,B,미공개,B,B,2019.0,NaN,NaN,NaN,NaN
4,10986.0,AJ네트웍스,095570,B,D,B,B,2020.0,NaN,NaN,NaN,NaN

In [12]:
# ESG 데이터 컬럼확인
evaluate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10990 entries, 0 to 10989
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   NO         10985 non-null  float64
 1   기업명        10985 non-null  object
 2   기업코드       10985 non-null  object
 3   ESG등급      10985 non-null  object
 4   환경         10985 non-null  object
 5   사회         10985 non-null  object
 6   지배구조       10985 non-null  object
 7   평가년도       10985 non-null  float64
 8   ESG 등급조정   167 non-null    object
 9   환경 등급조정    57 non-null     object
 10  사회 등급조정    277 non-null    object
 11  지배구조 등급조정  217 non-null    object
dtypes: float64(2), object(10)
memory usage: 1.0+ MB

In [39]:
# 기업명, 기업코드, ESG 등급, 환경, 사회, 지배구조, 평가년도 컬럼만 사용하자
ev_df = evaluate_df.drop(columns={
    'NO','ESG 등급조정','환경 등급조정','사회 등급조정','지배구조 등급조정'
})
ev_df.head()

      기업명    기업코드 ESG등급   환경   사회 지배구조    평가년도
0  AJ네트웍스  095570   미공개  미공개  미공개    C  2016.0
1  AJ네트웍스  095570   미공개  미공개  미공개    B  2017.0
2  AJ네트웍스  095570   미공개  미공개  미공개    C  2018.0
3  AJ네트웍스  095570     B  미공개    B    B  2019.0
4  AJ네트웍스  095570     B    D    B    B  2020.0

In [40]:
# 평가년도 확인 2012년은 제거 -> 706개 
# 2013년부터 ESG 등급체계 달라짐
# 10284개 행
ev_df = ev_df[~(ev_df['평가년도'] == 2012)]
# ev_df.to_excel('ev_df_v1.xlsx')

In [ ]:
# ESG등급 등급없음 제거 -> 345개 제거 : 9939개 
# ESG등급, 환경, 사회, 지배구조 모두 미공개면 제거 -> 18개 제거 : 9921개
ev_df = ev_df[~(ev_df['ESG등급'] == '등급없음')]
flag1 = (ev_df['ESG등급'] == '미공개')
flag2 = (ev_df['환경'] == '미공개')
flag3 = (ev_df['사회'] == '미공개')
flag4 = (ev_df['지배구조'] == '미공개')
ev_df[~flag1 & (flag2 | flag3 | flag4)]

           기업명    기업코드 ESG등급   환경   사회 지배구조    평가년도
3       AJ네트웍스  095570     B  미공개    B    B  2019.0
22       AK홀딩스  006840     B  미공개    B    B  2019.0
33         BGF  027410     B  미공개    A    B  2019.0
39      BGF리테일  282330     B  미공개   B+   B+  2019.0
47     BNK금융지주  138930    B+  미공개    A    A  2013.0
...        ...     ...   ...  ...  ...  ...     ...
10933      휴온스  243070     B  미공개   B+    B  2019.0
10939   휴온스글로벌  084110     B  미공개   B+   B+  2019.0
10968     흥국화재  000540    B+  미공개  미공개   A+  2016.0
10969     흥국화재  000540    B+  미공개  미공개    A  2017.0
10971     흥국화재  000540     B  미공개    B    B  2019.0

[514 rows x 7 columns]

In [ ]:
# 평가없음 = 0, D = 1, C = 2, B = 3, B+ = 4, A = 5, A+ = 6 점으로 계량화
for idx, row in ev_df.iterrows():
    print(idx)
    print(row)

0
기업명      AJ네트웍스
기업코드     095570
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2016.0
Name: 0, dtype: object
1
기업명      AJ네트웍스
기업코드     095570
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2017.0
Name: 1, dtype: object
2
기업명      AJ네트웍스
기업코드     095570
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2018.0
Name: 2, dtype: object
3
기업명      AJ네트웍스
기업코드     095570
ESG등급         B
환경          미공개
사회            B
지배구조          B
평가년도     2019.0
Name: 3, dtype: object
4
기업명      AJ네트웍스
기업코드     095570
ESG등급         B
환경            D
사회            B
지배구조          B
평가년도     2020.0
Name: 4, dtype: object
5
기업명      AJ네트웍스
기업코드     095570
ESG등급         B
환경            D
사회            B
지배구조          B
평가년도     2021.0
Name: 5, dtype: object
6
기업명      AJ네트웍스
기업코드     095570
ESG등급        B+
환경            C
사회           B+
지배구조         B+
평가년도     2022.0
Name: 6, dtype: object
7
기업명      AJ네트웍스
기업코드     095570
ESG등급        B+
환경            C
사회            A
지배구조         B+
평가년도     2023.0
Name: 7, dtype: object
8
기업명      AJ네트웍스
기업코드     095570
ESG등급        B+
환경            C
사회            A
지배구조         B+
평가년도     2024.0
Name: 8, dtype: object
9
기업명       AJ렌터카
기업코드     068400
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2014.0
Name: 9, dtype: object
10
기업명       AJ렌터카
기업코드     068400
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2015.0
Name: 10, dtype: object
11
기업명       AJ렌터카
기업코드     068400
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2016.0
Name: 11, dtype: object
12
기업명       AJ렌터카
기업코드     068400
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2017.0
Name: 12, dtype: object
13
기업명       AJ렌터카
기업코드     068400
ESG등급       미공개
환경           B+
사회          미공개
지배구조          B
평가년도     2018.0
Name: 13, dtype: object
14
기업명       AJ렌터카
기업코드     068400
ESG등급       미공개
환경            B
사회            B
지배구조          C
평가년도     2019.0
Name: 14, dtype: object
16
기업명       AK홀딩스
기업코드     006840
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2013.0
Name: 16, dtype: object
17
기업명       AK홀딩스
기업코드     006840
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2014.0
Name: 17, dtype: object
18
기업명       AK홀딩스
기업코드     006840
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2015.0
Name: 18, dtype: object
19
기업명       AK홀딩스
기업코드     006840
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2016.0
Name: 19, dtype: object
20
기업명       AK홀딩스
기업코드     006840
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2017.0
Name: 20, dtype: object
21
기업명       AK홀딩스
기업코드     006840
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2018.0
Name: 21, dtype: object
22
기업명       AK홀딩스
기업코드     006840
ESG등급         B
환경          미공개
사회            B
지배구조          B
평가년도     2019.0
Name: 22, dtype: object
23
기업명       AK홀딩스
기업코드     006840
ESG등급        B+
환경            C
사회           B+
지배구조         B+
평가년도     2020.0
Name: 23, dtype: object
24
기업명       AK홀딩스
기업코드     006840
ESG등급        B+
환경            B
사회           B+
지배구조         B+
평가년도     2021.0
Name: 24, dtype: object
25
기업명       AK홀딩스
기업코드     006840
ESG등급        B+
환경            B
사회            A
지배구조          B
평가년도     2022.0
Name: 25, dtype: object
26
기업명       AK홀딩스
기업코드     006840
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2023.0
Name: 26, dtype: object
27
기업명       AK홀딩스
기업코드     006840
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2024.0
Name: 27, dtype: object
28
기업명       AP시스템
기업코드     265520
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2019.0
Name: 28, dtype: object
29
기업명       AP시스템
기업코드     265520
ESG등급         D
환경            D
사회            D
지배구조          C
평가년도     2021.0
Name: 29, dtype: object
30
기업명       AP시스템
기업코드     265520
ESG등급         D
환경            D
사회            C
지배구조          C
평가년도     2022.0
Name: 30, dtype: object
31
기업명         BGF
기업코드     027410
ESG등급       미공개
환경          미공개
사회           B+
지배구조          B
평가년도     2016.0
Name: 31, dtype: object
32
기업명         BGF
기업코드     027410
ESG등급       미공개
환경          미공개
사회            A
지배구조          B
평가년도     2017.0
Name: 32, dtype: object
33
기업명         BGF
기업코드     027410
ESG등급         B
환경          미공개
사회            A
지배구조          B
평가년도     2019.0
Name: 33, dtype: object
34
기업명         BGF
기업코드     027410
ESG등급        B+
환경            B
사회            A
지배구조         B+
평가년도     2020.0
Name: 34, dtype: object
35
기업명         BGF
기업코드     027410
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2021.0
Name: 35, dtype: object
36
기업명         BGF
기업코드     027410
ESG등급        B+
환경            A
사회           A+
지배구조          B
평가년도     2022.0
Name: 36, dtype: object
37
기업명         BGF
기업코드     027410
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2023.0
Name: 37, dtype: object
38
기업명         BGF
기업코드     027410
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2024.0
Name: 38, dtype: object
39
기업명      BGF리테일
기업코드     282330
ESG등급         B
환경          미공개
사회           B+
지배구조         B+
평가년도     2019.0
Name: 39, dtype: object
40
기업명      BGF리테일
기업코드     282330
ESG등급         A
환경           B+
사회           B+
지배구조          A
평가년도     2020.0
Name: 40, dtype: object
41
기업명      BGF리테일
기업코드     282330
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2021.0
Name: 41, dtype: object
42
기업명      BGF리테일
기업코드     282330
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2022.0
Name: 42, dtype: object
43
기업명      BGF리테일
기업코드     282330
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2023.0
Name: 43, dtype: object
44
기업명      BGF리테일
기업코드     282330
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2024.0
Name: 44, dtype: object
45
기업명      BGF에코머티리얼즈
기업코드         126600
ESG등급             B
환경                B
사회                B
지배구조              B
평가년도         2024.0
Name: 45, dtype: object
47
기업명      BNK금융지주
기업코드      138930
ESG등급         B+
환경           미공개
사회             A
지배구조           A
평가년도      2013.0
Name: 47, dtype: object
48
기업명      BNK금융지주
기업코드      138930
ESG등급          A
환경           미공개
사회             A
지배구조          A+
평가년도      2014.0
Name: 48, dtype: object
49
기업명      BNK금융지주
기업코드      138930
ESG등급          A
환경           미공개
사회             A
지배구조          A+
평가년도      2015.0
Name: 49, dtype: object
50
기업명      BNK금융지주
기업코드      138930
ESG등급          A
환경           미공개
사회            B+
지배구조          A+
평가년도      2016.0
Name: 50, dtype: object
51
기업명      BNK금융지주
기업코드      138930
ESG등급         B+
환경            B+
사회             A
지배구조           B
평가년도      2017.0
Name: 51, dtype: object
52
기업명      BNK금융지주
기업코드      138930
ESG등급         B+
환경           미공개
사회            B+
지배구조         미공개
평가년도      2018.0
Name: 52, dtype: object
53
기업명      BNK금융지주
기업코드      138930
ESG등급         A+
환경            B+
사회            A+
지배구조          A+
평가년도      2019.0
Name: 53, dtype: object
54
기업명      BNK금융지주
기업코드      138930
ESG등급         A+
환경            B+
사회            A+
지배구조          A+
평가년도      2020.0
Name: 54, dtype: object
55
기업명      BNK금융지주
기업코드      138930
ESG등급         A+
환경             A
사회            A+
지배구조          A+
평가년도      2021.0
Name: 55, dtype: object
56
기업명      BNK금융지주
기업코드      138930
ESG등급          A
환경             A
사회             A
지배구조           A
평가년도      2022.0
Name: 56, dtype: object
57
기업명      BNK금융지주
기업코드      138930
ESG등급          A
환경             A
사회            A+
지배구조           A
평가년도      2023.0
Name: 57, dtype: object
58
기업명      BNK금융지주
기업코드      138930
ESG등급          A
환경            A+
사회            A+
지배구조           A
평가년도      2024.0
Name: 58, dtype: object
65
기업명         BYC
기업코드     001460
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2013.0
Name: 65, dtype: object
66
기업명         BYC
기업코드     001460
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2014.0
Name: 66, dtype: object
67
기업명         BYC
기업코드     001460
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2015.0
Name: 67, dtype: object
68
기업명         BYC
기업코드     001460
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2016.0
Name: 68, dtype: object
69
기업명         BYC
기업코드     001460
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2017.0
Name: 69, dtype: object
70
기업명         BYC
기업코드     001460
ESG등급       미공개
환경          미공개
사회          미공개
지배구조         B+
평가년도     2018.0
Name: 70, dtype: object
71
기업명         BYC
기업코드     001460
ESG등급         B
환경          미공개
사회           B+
지배구조         B+
평가년도     2019.0
Name: 71, dtype: object
72
기업명         BYC
기업코드     001460
ESG등급         B
환경            D
사회            B
지배구조         B+
평가년도     2020.0
Name: 72, dtype: object
73
기업명         BYC
기업코드     001460
ESG등급         B
환경            D
사회            B
지배구조         B+
평가년도     2021.0
Name: 73, dtype: object
74
기업명         BYC
기업코드     001460
ESG등급         D
환경            D
사회            D
지배구조          D
평가년도     2022.0
Name: 74, dtype: object
75
기업명         BYC
기업코드     001460
ESG등급         D
환경            D
사회            D
지배구조          D
평가년도     2023.0
Name: 75, dtype: object
76
기업명         BYC
기업코드     001460
ESG등급         D
환경            D
사회            D
지배구조          C
평가년도     2024.0
Name: 76, dtype: object
78
기업명          CJ
기업코드     001040
ESG등급        B+
환경          미공개
사회            A
지배구조          B
평가년도     2013.0
Name: 78, dtype: object
79
기업명          CJ
기업코드     001040
ESG등급        B+
환경           B+
사회            A
지배구조          B
평가년도     2014.0
Name: 79, dtype: object
80
기업명          CJ
기업코드     001040
ESG등급        B+
환경           B+
사회            A
지배구조          B
평가년도     2015.0
Name: 80, dtype: object
81
기업명          CJ
기업코드     001040
ESG등급        B+
환경           B+
사회            A
지배구조         B+
평가년도     2016.0
Name: 81, dtype: object
82
기업명          CJ
기업코드     001040
ESG등급         A
환경          미공개
사회            A
지배구조          A
평가년도     2017.0
Name: 82, dtype: object
83
기업명          CJ
기업코드     001040
ESG등급         A
환경          미공개
사회           A+
지배구조          A
평가년도     2018.0
Name: 83, dtype: object
84
기업명          CJ
기업코드     001040
ESG등급         A
환경            B
사회           A+
지배구조          A
평가년도     2019.0
Name: 84, dtype: object
85
기업명          CJ
기업코드     001040
ESG등급         A
환경            B
사회            A
지배구조          A
평가년도     2020.0
Name: 85, dtype: object
86
기업명          CJ
기업코드     001040
ESG등급         A
환경           B+
사회           A+
지배구조          A
평가년도     2021.0
Name: 86, dtype: object
87
기업명          CJ
기업코드     001040
ESG등급        B+
환경           B+
사회            A
지배구조         B+
평가년도     2022.0
Name: 87, dtype: object
88
기업명          CJ
기업코드     001040
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2023.0
Name: 88, dtype: object
89
기업명          CJ
기업코드     001040
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2024.0
Name: 89, dtype: object
91
기업명      CJ CGV
기업코드     079160
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2013.0
Name: 91, dtype: object
92
기업명      CJ CGV
기업코드     079160
ESG등급       미공개
환경          미공개
사회           B+
지배구조          C
평가년도     2014.0
Name: 92, dtype: object
93
기업명      CJ CGV
기업코드     079160
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2015.0
Name: 93, dtype: object
94
기업명      CJ CGV
기업코드     079160
ESG등급       미공개
환경          미공개
사회           B+
지배구조          C
평가년도     2016.0
Name: 94, dtype: object
95
기업명      CJ CGV
기업코드     079160
ESG등급       미공개
환경          미공개
사회           B+
지배구조         B+
평가년도     2017.0
Name: 95, dtype: object
96
기업명      CJ CGV
기업코드     079160
ESG등급        B+
환경          미공개
사회           B+
지배구조          A
평가년도     2018.0
Name: 96, dtype: object
97
기업명      CJ CGV
기업코드     079160
ESG등급        B+
환경            B
사회           B+
지배구조          A
평가년도     2019.0
Name: 97, dtype: object
98
기업명      CJ CGV
기업코드     079160
ESG등급         A
환경            B
사회            A
지배구조          A
평가년도     2020.0
Name: 98, dtype: object
99
기업명      CJ CGV
기업코드     079160
ESG등급         A
환경            B
사회            A
지배구조          A
평가년도     2021.0
Name: 99, dtype: object
100
기업명      CJ CGV
기업코드     079160
ESG등급        B+
환경            B
사회           B+
지배구조         B+
평가년도     2022.0
Name: 100, dtype: object
101
기업명      CJ CGV
기업코드     079160
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2023.0
Name: 101, dtype: object
102
기업명      CJ CGV
기업코드     079160
ESG등급         A
환경           A+
사회           A+
지배구조          A
평가년도     2024.0
Name: 102, dtype: object
103
기업명      CJ ENM
기업코드     035760
ESG등급         B
환경          미공개
사회           B+
지배구조         B+
평가년도     2019.0
Name: 103, dtype: object
104
기업명      CJ ENM
기업코드     035760
ESG등급        B+
환경            C
사회            A
지배구조          A
평가년도     2020.0
Name: 104, dtype: object
105
기업명      CJ ENM
기업코드     035760
ESG등급         A
환경            B
사회           A+
지배구조          A
평가년도     2021.0
Name: 105, dtype: object
106
기업명      CJ ENM
기업코드     035760
ESG등급        B+
환경           B+
사회            A
지배구조          B
평가년도     2022.0
Name: 106, dtype: object
107
기업명      CJ ENM
기업코드     035760
ESG등급        B+
환경           B+
사회           A+
지배구조          B
평가년도     2023.0
Name: 107, dtype: object
108
기업명      CJ ENM
기업코드     035760
ESG등급         A
환경           B+
사회           A+
지배구조         B+
평가년도     2024.0
Name: 108, dtype: object
109
기업명      CJ 바이오사이언스
기업코드         311690
ESG등급             C
환경                D
사회                C
지배구조              B
평가년도         2023.0
Name: 109, dtype: object
110
기업명      CJ 바이오사이언스
기업코드         311690
ESG등급            B+
환경                C
사회               B+
지배구조             B+
평가년도         2024.0
Name: 110, dtype: object
112
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경           B+
사회            A
지배구조         B+
평가년도     2013.0
Name: 112, dtype: object
113
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경           B+
사회            A
지배구조         B+
평가년도     2014.0
Name: 113, dtype: object
114
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경           B+
사회           B+
지배구조         B+
평가년도     2015.0
Name: 114, dtype: object
115
기업명      CJ대한통운
기업코드     000120
ESG등급         A
환경            A
사회            A
지배구조         B+
평가년도     2016.0
Name: 115, dtype: object
116
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경            A
사회           B+
지배구조         B+
평가년도     2017.0
Name: 116, dtype: object
117
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경            A
사회           B+
지배구조         B+
평가년도     2018.0
Name: 117, dtype: object
118
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경            A
사회           B+
지배구조         B+
평가년도     2019.0
Name: 118, dtype: object
119
기업명      CJ대한통운
기업코드     000120
ESG등급         A
환경            A
사회            B
지배구조          A
평가년도     2020.0
Name: 119, dtype: object
120
기업명      CJ대한통운
기업코드     000120
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2021.0
Name: 120, dtype: object
121
기업명      CJ대한통운
기업코드     000120
ESG등급        B+
환경           B+
사회           A+
지배구조          B
평가년도     2022.0
Name: 121, dtype: object
122
기업명      CJ대한통운
기업코드     000120
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2023.0
Name: 122, dtype: object
123
기업명      CJ대한통운
기업코드     000120
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2024.0
Name: 123, dtype: object
125
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          C
평가년도     2013.0
Name: 125, dtype: object
126
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2014.0
Name: 126, dtype: object
127
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경           B+
사회          미공개
지배구조          B
평가년도     2015.0
Name: 127, dtype: object
128
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2016.0
Name: 128, dtype: object
129
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경          미공개
사회          미공개
지배구조          B
평가년도     2017.0
Name: 129, dtype: object
130
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경          미공개
사회           B+
지배구조          B
평가년도     2018.0
Name: 130, dtype: object
131
기업명       CJ씨푸드
기업코드     011150
ESG등급       미공개
환경          미공개
사회          미공개
지배구조         B+
평가년도     2019.0
Name: 131, dtype: object
132
기업명       CJ씨푸드
기업코드     011150
ESG등급         B
환경            C
사회           B+
지배구조         B+
평가년도     2020.0
Name: 132, dtype: object
133
기업명       CJ씨푸드
기업코드     011150
ESG등급         B
환경            C
사회           B+
지배구조         B+
평가년도     2021.0
Name: 133, dtype: object
134
기업명       CJ씨푸드
기업코드     011150
ESG등급         B
환경            C
사회            B
지배구조          B
평가년도     2022.0
Name: 134, dtype: object
135
기업명       CJ씨푸드
기업코드     011150
ESG등급        B+
환경           B+
사회            A
지배구조          B
평가년도     2023.0
Name: 135, dtype: object
136
기업명       CJ씨푸드
기업코드     011150
ESG등급        B+
환경            A
사회            A
지배구조          B
평가년도     2024.0
Name: 136, dtype: object
138
기업명      CJ제일제당
기업코드     097950
ESG등급        B+
환경            A
사회            A
지배구조          B
평가년도     2013.0
Name: 138, dtype: object
139
기업명      CJ제일제당
기업코드     097950
ESG등급        B+
환경            A
사회            A
지배구조          B
평가년도     2014.0
Name: 139, dtype: object
140
기업명      CJ제일제당
기업코드     097950
ESG등급        B+
환경            A
사회           B+
지배구조          B
평가년도     2015.0
Name: 140, dtype: object
141
기업명      CJ제일제당
기업코드     097950
ESG등급        B+
환경            A
사회           B+
지배구조          B
평가년도     2016.0
Name: 141, dtype: object
142
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회            A
지배구조         B+
평가년도     2017.0
Name: 142, dtype: object
143
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회           A+
지배구조         B+
평가년도     2018.0
Name: 143, dtype: object
144
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2019.0
Name: 144, dtype: object
145
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2020.0
Name: 145, dtype: object
146
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2021.0
Name: 146, dtype: object
147
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회            A
지배구조         B+
평가년도     2022.0
Name: 147, dtype: object
148
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회           A+
지배구조          A
평가년도     2023.0
Name: 148, dtype: object
149
기업명      CJ제일제당
기업코드     097950
ESG등급         A
환경            A
사회            A
지배구조         B+
평가년도     2024.0
Name: 149, dtype: object
150
기업명      CJ프레시웨이
기업코드      051500
ESG등급          A
환경             B
사회             A
지배구조           A
평가년도      2019.0
Name: 150, dtype: object
151
기업명      CJ프레시웨이
기업코드      051500
ESG등급          A
환경             B
사회            A+
지배구조           A
평가년도      2020.0
Name: 151, dtype: object
152
기업명      CJ프레시웨이
기업코드      051500
ESG등급          A
환경             B
사회             A
지배구조           A
평가년도      2021.0
Name: 152, dtype: object
153
기업명      CJ프레시웨이
기업코드      051500
ESG등급          A
환경             B
사회             A
지배구조           A
평가년도      2022.0
Name: 153, dtype: object
154
기업명      CJ프레시웨이
기업코드      051500
ESG등급          A
환경            B+
사회            A+
지배구조           A
평가년도      2023.0

In [ ]:
df